name: Multi-Job demo

on:
  push:
    branches: [main]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my code
        uses: actions/checkout@v4

      - name: list all files
        run: ls -la

      - name: check index.html exists
        run: echo "Files look good"

  notify-done:
    needs: check-files
    runs-on: ubuntu-latest

    steps:
      - name: Notify that the job is done
        run: echo "All jobs are done!"